#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""GitHub explorer

Searches for repos based on a query and returns their ssh url

Can be fed into fzf, git, and xargs for interactive git cloning

Example: ghex "silver searcher ag" | fzf | xargs git clone

"""

import sys
import configparser
from pathlib import Path

import github3

cp = configparser.ConfigParser()
CONFIG_PATH = str(Path.home()) + '/.config/ghex.conf'
cp.read(CONFIG_PATH)
username = cp['credentials']['username']
password = cp['credentials']['password']

github = github3.login(username=username, password=password)

if len(sys.argv) < 2:
    sys.exit(1)

query = sys.argv[1]

repos = github.search_repositories(query=query)
for repo in repos:
    print(getattr(repo, "ssh_url"))
