#!/usr/bin/python3
import sys
import hashlib


# init vars
s = sys.argv[1]

PIN_LENGTH = 4
if len(sys.argv) > 2:
    PIN_LENGTH = int(sys.argv[2])

SALT = ''
if len(sys.argv) > 3:
    SALT = sys.argv[3]
to_encode = s + SALT

# compute code
code = int(hashlib.sha256(to_encode.encode('utf-8'))
        .hexdigest(), 16) % 10 ** PIN_LENGTH

# print code
FORMAT_STR = "{:0" + str(PIN_LENGTH) + "d}"
print(FORMAT_STR.format(code))
